version: "3"
services:
  db:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: fixme_backend_production
      POSTGRES_USER: USER

  caddy:
    image: abiosoft/caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - 80:80
      - 443:443

  web:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://USER:PASSWORD@db:5432/fixme_backend_production?sslmode=disable"
      GITHUB_TOKEN: 
      JWT_SECRET: "123"
    links:
      - db:db
